title: David Lattimore's Blog
email: dvdlttmr@gmail.com
description: >- # ignore newlines until "baseurl:"
  A blog about my open-source work, mostly in Rust. My interests are mostly around developer
  tooling, compilers, linking.
github_username:  davidlattimore

plugins:
  - jekyll-feed
  - jekyll-redirect-from
